import { Metadata } from 'next';

import './globals.css';
import Providers from './providers';
import TopNavigation from '@/components/TopNavigation';
import SideMenu from '@/components/SideMenu';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<Providers>
					<TopNavigation />
					<div className='grid grid-cols-4'>
						<SideMenu />
						<main className='col-span-3 h-full max-h-[calc(100dvh-64px)] overflow-hidden'>
							{children}
						</main>
					</div>
				</Providers>
			</body>
		</html>
	);
}
