import { Metadata } from 'next';

import './globals.css';
import Providers from './providers';
import TopNavigation from '@/components/TopNavigation';
import Footer from './_components/footer';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className='mx-auto max-w-screen-md'>
				<Providers>
					<TopNavigation />
					<main className=''>
						<div className='w-full flex justify-center'>{children}</div>
					</main>
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
