import Metadata from 'next';

import './globals.css';
import Providers from './providers';
import BottomNavigation from '@/components/BottomNavigation';
import TopNavigation from '@/components/TopNavigation';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<Providers>
					<TopNavigation />
					<main>{children}</main>
					<BottomNavigation />
				</Providers>
			</body>
		</html>
	);
}
