import { Metadata } from 'next';

import '../../globals.css';
import Providers from '@/app/providers';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<Providers>
					<main className='h-dvh mx-auto max-w-screen-md '>
						<div className='h-full w-full flex justify-center'>{children}</div>
					</main>
				</Providers>
			</body>
		</html>
	);
}
