import { Metadata } from "next";

import "../../globals.css";
import Providers from "@/app/(providers)/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="grid-container">
            <div className="subgrid-container">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
