import { Metadata } from 'next';
import Footer from './_components/footer';
import TopNavigation from '@/components/top-navigation/top-navigation';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<TopNavigation />
			<main className='mx-auto max-w-screen-md'>
				<div className='w-full flex justify-center'>{children}</div>
			</main>
			<Footer />
		</>
	);
}
